### ISSUE TITLE
make fa2_modified work with scanpy

### ISSUE THREAD

**Issue by wfaalajr** [AminAlam/forceatlas2_maintained#2]
Hi! Thanks for making this modified version. I was able to successfully install this version, but when I try using it in scanpy, i.e.:

```
adata = sc.read_h5ad("myadata.h5ad")
sc.pp.filter_genes(adata, min_cells=10)
scv.pp.normalize_per_cell(adata)
sc.pp.log1p(adata)
sc.pp.highly_variable_genes(adata)
sc.pp.neighbors(adata)
sc.tl.draw_graph(adata)
```

scanpy does not detect this version and throws out this message:

WARNING: Package 'fa2' is not installed, falling back to layout 'fr'.To use the faster and better ForceAtlas2 layout, install package 'fa2' (`pip install fa2`).

I am on python3.11.

Any recommendations from your end would be really awesome :)

**Comment by n-elie** [comment]
Hi, would be better to report this [upstream](https://github.com/scverse/scanpy).
It seems that this subject has already been discussed [here](https://github.com/scverse/scanpy/issues/2067)

**Comment by AminAlam** [comment]
@wfaalajr I've made this [PR](https://github.com/scverse/scanpy/pull/3220) to fix the problem you mentioned in Scapy by using fa2_modified instead of fa2.

**Comment by AminAlam** [comment]
I'll close this issue as https://github.com/scverse/scanpy/pull/3220 is closed now
